name: mkdocs

on:
  workflow_run:
    workflows: ["Create Docs"]
    types:
    - completed
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: install mkdocs
      run: pip install mkdocs
    - name: mkdocs deploy
      run: mkdocs gh-deploy --clean
